
CREATE TABLE USERS (
    ID INT NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    ADDRESS VARCHAR(150) NOT NULL,
    SYS_START TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
    SYS_END TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
    TRANS_START TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    PERIOD SYSTEM_TIME(SYS_START, SYS_END)
    PRIMARY KEY (ID)
);

CREATE TABLE USERS_HYSTORY LIKE USERS;

ALTER TABLE USERS ADD versioning use HISTORY TABLE ourse_sys_history

CREATE TABLE CARS(
    YEAR INT NOT NULL,
    MODEL VARCHAR(30) NOT NULL,
    BRAND VARCHAR(30) NOT NULL,
    PRICE DECIMAL NOT NULL,
    INVOICE INT NOT NULL,
    MOTOR_NUM INT NOT NULL,
    SERIES_NUM INT NOT NULL,
);

CREATE TABLE INSURANCE(
    PRICE DECIMAL(6,2) NOT NULL,
    COVERAGE VARCHAR(50) NOT NULL,
    SYS_START TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
    SYS_END TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
    TRANS_START TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
    PERIOD SYSTEM_TIME(SYS_START, SYS_END)
)
